export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const REMOVE_FAVOURITE = "REMOVE_FAVOURITE";
export const INCREMENT_FAVOURITES = "INCREMENT_FAVOURITES";
export const DECREMENT_FAVOURITES = "DECREMENT_FAVOURITES";
