import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Partyking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-10">Hello Partyking</main>
    </div>
  );
}
