import Head from "next/head";
import { useArticle } from "../hooks/articles";
import { getDimensionInfo } from "../utils/boxUtils";
import FetchArticleForm from "../components/forms/FetchArticleForm/FetchArticleForm";
import { useEffect, useState } from "react";

const Home = () => {
  const { fetchArticle } = useArticle();
  const [boxes, setBoxes] = useState([]);
  const [article, setArticle] = useState(null);
  const [fittableBoxes, setFittableBoxes] = useState([]);
  const handleSubmit = async (value) => {
    await fetchArticle(value)
      .then((response) => setArticle(response))
      .catch((error) => console.log(error));
  };

  useEffect(() => {
    if (boxes.length === 0) {
      fetch("/api/boxes/sizes")
        .then((response) => response.json())
        .then((result) => setBoxes(result));
    }
    if (article) {
      boxes.forEach((box) => {
        console.log(getDimensionInfo(article.variant_first_buyable, box));
      });
    }
  }, [boxes, article]);
  return (
    <div>
      <Head>
        <title>Partyking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{article && article.name}</div>
      <div className="h-screen w-full flex flex-col items-center justify-center">
        <FetchArticleForm loading onSubmit={(value) => handleSubmit(value)} />
      </div>
    </div>
  );
};

export default Home;
