import Head from "next/head";
import { useEffect, useState } from "react";
import { useArticle } from "../hooks/articles";

const Home = () => {
  const { fetchArticle, loading, error } = useArticle();

  const handleFetchArticle = async () => {
    const article = await fetchArticle(12332);
    console.log(article);
  };

  useEffect(() => {
    handleFetchArticle();
  }, []);
  return (
    <div>
      <Head>
        <title>Partyking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
